### ISSUE TITLE
Misformatted text

### ISSUE THREAD

**Issue by cptcanuck** [PiercingDan/spark-Jupyter-AWS#3]
It looks like you meant to put a code block around this section:

[ec2-user@privateipaddress]$ lsblk 
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT xvda 202:0 0 10G 0 disk └─xvda1 202:1 0 10G 0 part / xvdf 202:80 0 30G 0 disk └─xvdf1 202:81 0 30G 0 part

then close the code block for hte rest of the list: 

6. Make a mount point `sudo mkdir /oldvol`, then mount the attached volume `sudo mount /dev/xvdf1 /oldvol`.

or it didn't close properly.  I don't have a nice envt where I can pull and submit a PR, so hopefully you can give it a quick fix.

**Comment by PiercingDan** [comment]
Fixed, thanks! Weird, It didn't used to look like that.
